In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import PolynomialFeatures
import warnings
warnings.filterwarnings("ignore")
np.random.seed(42)

In [49]:
df = pd.read_csv ("C:\\Users\\YB998DQ\\Downloads\\loan_data.csv", sep = ',')
y = df.pop('not.fully.paid')

In [50]:
df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   credit.policy      9578 non-null   int64
 1   purpose            9578 non-null   object
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64
 11  delinq.2yrs        9578 non-null   int64
 12  pub.rec            9578 non-null   int64
dtypes: float64(6), int64(6), object(1)
memory usage: 972.9+ KB

In [52]:
dummies = pd.get_dummies(df['purpose'])
dummies.head()

,all_other,credit_card,debt_consolidation,educational,home_improvement,major_purchase,small_business
0,0,0,1,0,0,0,0
1,0,1,0,0,0,0,0
2,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0
4,0,1,0,0,0,0,0

In [45]:
df = pd.concat([df,dummies],axis=1)
df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,...,home_improvement,major_purchase,small_business,all_other,credit_card,debt_consolidation,educational,home_improvement,major_purchase,small_business
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,...,0,0,0,0,0,1,0,0,0,0
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,...,0,0,0,0,1,0,0,0,0,0
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,...,0,0,0,0,0,1,0,0,0,0
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,...,0,0,0,0,0,1,0,0,0,0
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,...,0,0,0,0,1,0,0,0,0,0

In [53]:
df.drop('purpose', axis=1,inplace=True)

In [54]:
df.head()

,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec
0,1,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0
1,1,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0
2,1,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0
3,1,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0
4,1,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0

In [55]:
concat_df = pd.concat([dummies,df],axis=1)

In [56]:
concat_df.head()

,all_other,credit_card,debt_consolidation,educational,home_improvement,major_purchase,small_business,credit.policy,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec
0,0,0,1,0,0,0,0,1,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0
1,0,1,0,0,0,0,0,1,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0
2,0,0,1,0,0,0,0,1,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0
3,0,0,1,0,0,0,0,1,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0
4,0,1,0,0,0,0,0,1,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0

In [75]:
train , test, y_train, y_test = train_test_split (concat_df, y, test_size = 0.2, random_state = 101)

In [76]:
lr = LogisticRegression()
lr.fit(train, y_train)
y_pred = lr.predict(test)
print ('Accuracy Score Baseline:', accuracy_score(y_test,y_pred))

Accuracy Score Baseline: 0.8460334029227558

In [77]:
def fit_predict (train, test, y_train, y_test, scalar, max_depth, criterion = 'entropy', max_features = 1, min_samples_split = 4):
    train_scaled = scalar.fit_transform(train)
    test_scaled = scalar.transform(test)
    dt = DecisionTreeClassifier(criterion=criterion, max_depth=max_depth,
                               random_state=42,max_features=max_features,
                               min_samples_split=min_samples_split)
    dt.fit(train_scaled,y_train)
    y_pred = dt.predict(test_scaled)
    print(accuracy_score(y_test,y_pred))

In [78]:
dt = DecisionTreeClassifier()
dt.fit(train,y_train)
y_pred = dt.predict(test)
print(accuracy_score(y_test,y_pred))

0.7301670146137788

In [79]:
for i in range (1,20):
    print('Accuracy score using max_depth =', i, end=': ')
    fit_predict(train,test,y_train,y_test,StandardScaler(),i)

Accuracy score using max_depth = 1: 0.8470772442588727
Accuracy score using max_depth = 2: 0.8470772442588727
Accuracy score using max_depth = 3: 0.8470772442588727
Accuracy score using max_depth = 4: 0.8470772442588727
Accuracy score using max_depth = 5: 0.8470772442588727
Accuracy score using max_depth = 6: 0.8455114822546973
Accuracy score using max_depth = 7: 0.8465553235908142
Accuracy score using max_depth = 8: 0.8434237995824635
Accuracy score using max_depth = 9: 0.8402922755741128
Accuracy score using max_depth = 10: 0.837160751565762
Accuracy score using max_depth = 11: 0.8355949895615866
Accuracy score using max_depth = 12: 0.8319415448851775
Accuracy score using max_depth = 13: 0.826722338204593
Accuracy score using max_depth = 14: 0.8308977035490606
Accuracy score using max_depth = 15: 0.81419624217119
Accuracy score using max_depth = 16: 0.7875782881002088
Accuracy score using max_depth = 17: 0.8021920668058455
Accuracy score using max_depth = 18: 0.8016701461377871
Accuracy score using max_depth = 19: 0.7870563674321504

In [80]:
for i in np.arange (0.1,1.0,0.1):
    print('Accuracy score using max features =', i, end=': ')
    fit_predict(train,test,y_train,y_test,StandardScaler(),max_depth=18, max_features = i)

Accuracy score using max features = 0.1: 0.8016701461377871
Accuracy score using max features = 0.2: 0.8006263048016702
Accuracy score using max features = 0.30000000000000004: 0.7870563674321504
Accuracy score using max features = 0.4: 0.784446764091858
Accuracy score using max features = 0.5: 0.7766179540709812
Accuracy score using max features = 0.6: 0.7729645093945721
Accuracy score using max features = 0.7000000000000001: 0.7625260960334029
Accuracy score using max features = 0.8: 0.7881002087682673
Accuracy score using max features = 0.9: 0.7667014613778705

In [81]:
for i in range (2,10):
    print('Accuracy score using min samples split =', i, end=': ')
    fit_predict(train,test,y_train,y_test,StandardScaler(),18, max_features = 0.3, min_samples_split=i)

Accuracy score using min samples split = 2: 0.7896659707724426
Accuracy score using min samples split = 3: 0.7802713987473904
Accuracy score using min samples split = 4: 0.7870563674321504
Accuracy score using min samples split = 5: 0.7922755741127349
Accuracy score using min samples split = 6: 0.8011482254697286
Accuracy score using min samples split = 7: 0.785490605427975
Accuracy score using min samples split = 8: 0.7886221294363257
Accuracy score using min samples split = 9: 0.7891440501043842

In [82]:
for i in ['gini','entropy']:
    print('Accuracy score using criterion =', i,end=':')
    fit_predict(train,test,y_train,y_test,StandardScaler(),18,
               max_features=0.3,min_samples_split=2,criterion=i)

Accuracy score using criterion = gini:0.7865344467640919
Accuracy score using criterion = entropy:0.7896659707724426

In [83]:
def create_poly (train,test,degree):
    poly = PolynomialFeatures(degree=degree)
    train_poly=poly.fit_transform(train)
    test_poly=poly.fit_transform(test)
    return train_poly, test_poly

In [84]:
for degree in [1,2,3,4]:
    train_poly, test_poly = create_poly(train,test,degree)
    print('polynomial degree',degree)
    fit_predict(train_poly,test_poly,y_train,y_test,StandardScaler(),18,
               max_features=0.3,min_samples_split=2,criterion='entropy')
    print (10*'-')

polynomial degree 1
0.7760960334029228
----------
polynomial degree 2
0.7719206680584552
----------
polynomial degree 3
0.7849686847599165
----------
polynomial degree 4
0.7635699373695198
----------

In [86]:
train_poly, test_poly = create_poly(train, test, 2)
fit_predict(train_poly,test_poly,y_train,y_test,StandardScaler(),18,
               max_features=0.3,min_samples_split=2,criterion='entropy')

0.7719206680584552

In [89]:
from sklearn.ensemble import RandomForestClassifier

In [90]:
rf = RandomForestClassifier(criterion = 'gini', oob_score=True)

In [91]:
rf.fit(train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [92]:
pred_rf = rf.predict(test)

In [93]:
from sklearn.metrics import accuracy_score
print (accuracy_score(y_test,pred_rf))

0.8449895615866388

In [94]:
from sklearn.model_selection import GridSearchCV

In [95]:
params = {'n_estimators':[200,500,700],'max_depth':[10,15,18,20],'min_samples_leaf':[3,5,7]}

In [96]:
gs = GridSearchCV(rf,params,verbose=3)

In [ ]:
gs.fit(train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.838, total=   1.6s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.5s remaining:    0.0s

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.838, total=   1.6s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    3.1s remaining:    0.0s

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.839, total=   1.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.837, total=   1.6s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.839, total=   1.6s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.838, total=   3.9s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.838, total=   4.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.839, total=   3.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.839, total=   3.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.838, total=   3.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.838, total=   5.5s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.838, total=   5.4s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.839, total=   5.3s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.838, total=   5.6s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.839, total=   5.3s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=200, score=0.838, total=   1.5s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=200, score=0.838, total=   1.5s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=200, score=0.838, total=   1.5s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=200, score=0.837, total=   1.6s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=200, score=0.838, total=   1.7s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=500, score=0.838, total=   3.9s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=500, score=0.838, total=   3.9s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=500, score=0.839, total=   3.8s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=500, score=0.837, total=   4.0s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=500, score=0.838, total=   3.8s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=700, score=0.838, total=   5.4s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=700, score=0.838, total=   5.3s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=700, score=0.839, total=   5.5s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=700, score=0.838, total=   5.3s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=700, score=0.838, total=   5.3s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=200, score=0.837, total=   1.7s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=200, score=0.838, total=   1.5s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=200, score=0.838, total=   1.5s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=200, score=0.838, total=   1.5s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=200, score=0.837, total=   1.5s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=500, score=0.837, total=   3.7s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=500, score=0.838, total=   3.7s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=500, score=0.838, total=   4.0s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=500, score=0.838, total=   3.9s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=500, score=0.838, total=   3.8s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=700, score=0.838, total=   5.3s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=700, score=0.838, total=   5.4s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=700, score=0.838, total=   5.3s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=700, score=0.838, total=   5.2s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=700, score=0.838, total=   5.4s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.840, total=   1.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.836, total=   1.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.839, total=   1.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.836, total=   1.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.837, total=   1.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.841, total=   5.1s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.837, total=   4.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.840, total=   4.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.839, total=   5.2s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.837, total=   4.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............

[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.840, total=   6.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.838, total=   7.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.838, total=   6.7s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.838, total=   7.1s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.836, total=   6.8s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.840, total=   1.9s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.838, total=   1.8s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.839, total=   1.9s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.839, total=   2.1s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.837, total=   1.9s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=500, score=0.839, total=   4.8s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=500, score=0.837, total=   4.6s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=500, score=0.839, total=   4.8s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=500, score=0.838, total=   4.6s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=500, score=0.837, total=   4.7s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=700, score=0.839, total=   6.7s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=700, score=0.838, total=   6.3s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=700, score=0.839, total=   6.3s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=700, score=0.837, total=   6.6s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=700, score=0.838, total=   6.4s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=200, score=0.839, total=   1.8s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=200, score=0.837, total=   1.8s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=200, score=0.839, total=   1.9s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=200, score=0.838, total=   1.8s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=200, score=0.837, total=   1.8s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=500, score=0.839, total=   4.4s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=500, score=0.838, total=   4.4s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=500, score=0.839, total=   4.7s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=500, score=0.838, total=   4.6s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=500, score=0.837, total=   4.6s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=700, score=0.838, total=   6.7s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=700, score=0.838, total=   6.4s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=700, score=0.839, total=   6.7s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=700, score=0.837, total=   6.9s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=700, score=0.839, total=   6.4s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.839, total=   2.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.836, total=   2.2s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.838, total=   2.1s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.837, total=   2.1s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.837, total=   2.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.840, total=   5.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.836, total=   5.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.839, total=   5.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.836, total=   4.9s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.836, total=   4.9s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.840, total=   7.1s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.839, total=   7.1s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.839, total=   7.3s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.838, total=   7.1s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.836, total=   7.3s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.839, total=   1.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.838, total=   2.1s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.839, total=   1.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............

[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.839, total=   1.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.837, total=   1.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.838, total=   4.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.838, total=   4.8s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.839, total=   4.7s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.838, total=   4.8s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.838, total=   4.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=700, score=0.840, total=   6.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=700 ..............

In [ ]:
gs.best_params_

In [ ]:
gs.best_estimator_

In [ ]:
rf1 = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=20, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=700,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
rf1.fit(train,y_train)

In [ ]:
rf1.oob_score_

In [ ]:
pred_rf1 = rf1.predict(test)

In [ ]:
print(accuracy_score(y_test,pred_rf1))

In [ ]:
rf1.feature_importances_

In [ ]:
sorted(list(zip(rf1.feature_importances_,df.columns)),reverse=True)